import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import Link from 'next/link'
import { getPages } from '@/sanity/lib/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Recipes',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader showSpinner={false} />
        <nav className="flex fixed top-0 items-center justify-between bg-teal-500 px-6 py-3 w-screen">
          <Link href="/">Recipes</Link>
          <div className="flex gap-4">
            {pages.map((page) => (
              <Link href={`/${page.slug}`} key={page._id}>{page.title}</Link>
              ))}
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
